version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
    commands:
      - echo Build started on `date`
      - echo "Current directory before navigation:"
      - pwd
      - ls -la
      
      # Navigate to project directory
      - cd 13-2048-game-codepipeline
      - echo "Current directory after navigation:"
      - pwd
      - ls -la
      
      # Build container image
      - echo Building container image...
      - docker build -f docker/Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      
      # Backend build only - frontend handled separately
      - echo Backend build completed
  
  post_build:
    commands:
      - echo Build completed on `date`
      
      # Push image to ECR
      - echo Pushing image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      # Update ECS service
      - echo Updating ECS service...
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
      
      # Backend deployment completed
      - echo Backend deployment completed

artifacts:
  files:
    - '**/*'