all:
  hosts:
    master-1:
      ansible_host: # Replace with actual IP from terraform output
      ip: # Replace with private IP
      access_ip: # Replace with private IP
    master-2:
      ansible_host: # Replace with actual IP from terraform output
      ip: # Replace with private IP
      access_ip: # Replace with private IP
    master-3:
      ansible_host: # Replace with actual IP from terraform output
      ip: # Replace with private IP
      access_ip: # Replace with private IP
    worker-1:
      ansible_host: # Replace with actual IP from terraform output
      ip: # Replace with private IP
      access_ip: # Replace with private IP
    worker-2:
      ansible_host: # Replace with actual IP from terraform output
      ip: # Replace with private IP
      access_ip: # Replace with private IP
    worker-3:
      ansible_host: # Replace with actual IP from terraform output
      ip: # Replace with private IP
      access_ip: # Replace with private IP
  children:
    kube_control_plane:
      hosts:
        master-1:
        master-2:
        master-3:
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:
    etcd:
      hosts:
        master-1:
        master-2:
        master-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'