# Backend Build Specification for CodeBuild
# This file defines the build process for the Flask API backend
# It builds a Docker container and deploys it to ECS Fargate

version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
      - REPOSITORY_URI=$ECR_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Build started on $(date)"
      - echo "Repository URI $REPOSITORY_URI"
      - echo "Image tag $IMAGE_TAG"
  build:
    commands:
      - echo "Current directory $(pwd)"
      - pwd && ls -la
      - cd 13-2048-game-aws-codepipeline
      - echo "Project directory $(pwd)"
      - ls -la
      - echo "Building Docker container image..."
      - docker build -f docker/Dockerfile -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo "Backend container build completed"
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Updating ECS service with new container..."
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
      - echo "Backend deployment completed successfully"
artifacts:
  files:
    - "**/*"
