apiVersion: apps/v1
kind: Deployment
metadata:
  name: hono-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hono-app
  template:
    metadata:
      labels:
        app: hono-app
    spec:
      containers:
        - name: hono-app
          image: omezh/hono-app:latest
          ports:
            - containerPort: 3000
