- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
