name: Deploy Project 3 - Custom Alexa Skill

on:
  push:
    branches:
      - main
    paths:
      - "03-custom-alexa-skill/lambda/**"
      - ".github/workflows/project3_customalexa.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 03-custom-alexa-skill/lambda

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Zip Lambda code
        run: |
          zip -r ../../lambda.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Deploy Lambda function
        run: aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME_PROJECT3 }} --zip-file fileb://lambda.zip
