name: Deploy Project 4 - Polly TTS Lambda

on:
  push:
    branches:
      - main
    paths:
      - "04-text-to-speech-polly/lambda/**"
      - ".github/workflows/04-text-to-speech-polly.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-text-to-speech-polly/lambda

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
          sudo apt-get install -y zip

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Check AWS credentials
        run: |
          aws sts get-caller-identity
          aws --version

      - name: Zip code
        run: |
          zip -r lambda4.zip index.js package.json

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME_PROJECT4 }}  --zip-file fileb://lambda4.zip
