name: Deploy Image Resizer

on:
  push:
    branches: [main]
    paths: ['06-smart-resize-images/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 06-smart-resize-images/infrastructure
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
          
      - name: Deploy infrastructure
        run: |
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_vercel_api_token: ${{ secrets.VERCEL_API_TOKEN }}
          TF_VAR_vercel_project_name: ${{ secrets.VERCEL_PROJECT_NAME }}
          
      - name: Trigger Vercel deployment
        run: |
          HOOK_URL=$(terraform output -raw vercel_deploy_hook_url)
          curl -X POST "$HOOK_URL"